version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: |
          pip install black
          black --check .
      - run: |
          pip install flake8
          flake8 setup.py smoothfit/ test/*.py
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3
    steps:
      - run: sudo apt-get update
      # For some reason ssh is needed; probably dolfin parallel?
      - run: apt-get install -y python3-pip python3-dolfin ssh
      - checkout
      # The actual test
      - run: |
          pip install tox
          tox
      # submit to codecov
      - run: |
          sudo apt-get install -y curl
          bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
