version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: |
          pip install black
          black --check .
      - run: |
          pip install flake8
          flake8 setup.py smoothfit/ test/*.py
  build:
    working_directory: ~/work
    docker:
      # This has to be an ubuntu base since we need python3-dolfin from system
      - image: ubuntu:19.04
    steps:
      - run: apt-get update
      # For some reason ssh is needed; probably dolfin parallel?
      - run: apt-get install -y python3-pip python3-dolfin ssh
      - run: pip3 install -U pytest pytest-cov
      - checkout
      - run: pip3 install .
      - run: pip3 install -r test_requirements.txt
      # The actual test
      - run:
          cmd: pytest --cov smoothfit
          working_directory: test
          env:
            MPLBACKEND: Agg
      # submit to codecov
      - run: |
          sudo apt-get install -y curl
          bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
