name: ci

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 smoothfit/ test/
    - name: Lint with black
      run: |
        pip install black
        black --check .

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # blas for numpy
    - name: Install system dependencies
      run: sudo apt-get install -y libblas-dev python3-dolfin
    - name: Add ~/.local/bin to $PATH
      # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
      run: echo "::add-path::/home/runner/.local/binr"
    - name: Update pip
      run: |
        python3 -m pip install --upgrade pip
        pip3 --version
    - name: Test with tox
      run: |
        python3 -m pip install tox
        tox
    - name: Submit to codecov
      run: bash <(curl -s https://codecov.io/bash)
